<script setup lang="ts">
import { BriefcaseBusiness, LayoutDashboard, Radar, Search, RefreshCw, MapPin, Clock3, ExternalLink, BookmarkPlus, Check, X, SlidersHorizontal, Sparkles, EyeOff, CircleDollarSign, RotateCcw, ArrowUpRight } from 'lucide-vue-next'
import type { DiscoveredJob } from '~/shared/types'
import { DISCOVERY_CATEGORIES } from '~/shared/types'

const searchDraft = ref(''), query = ref(''), source = ref('all'), region = ref('bangkok'), category = ref('all'), employment = ref('all'), minSalary = ref(0), salaryOnly = ref(false), showDismissed = ref(false), visibleCount = ref(36), refreshToken = ref(0)
const toast = ref(''), saving = ref(new Set<string>())
const params = computed(() => ({ q:query.value, source:source.value, region:region.value, category:category.value, employment:employment.value, minSalary:minSalary.value||undefined, salaryOnly:salaryOnly.value?'1':undefined, ...(refreshToken.value ? {refresh:'1'} : {}) }))
type DiscoverResponse = { jobs:DiscoveredJob[]; fetchedAt:string; facets:{total:number;afterCategory:number;salaryDisclosed:number;categories:Record<string,number>;salaryThresholds:Record<string,number>} }
const emptyFacets = {total:0,afterCategory:0,salaryDisclosed:0,categories:{},salaryThresholds:{}}
const { data, pending, error, refresh } = await useFetch<DiscoverResponse>('/api/discover', { query:params, default:()=>({jobs:[],fetchedAt:'',facets:emptyFacets}), watch:[source,region,query,category,employment,minSalary,salaryOnly] })
const jobs = computed(() => data.value.jobs.filter(j => showDismissed.value || !j.isDismissed))
const visible = computed(() => jobs.value.slice(0,visibleCount.value))
const hiddenCount = computed(() => data.value.jobs.filter(j=>j.isDismissed).length)
const newCount = computed(() => jobs.value.filter(j=>isNew(j.postedAt)).length)
const disclosedSalaryCount = computed(() => jobs.value.filter(j=>j.salary).length)
const localSalary = computed(() => ['bangkok','thailand'].includes(region.value))
const jobsDbUrl = computed(() => {
  const keyword = (query.value || (category.value !== 'all' ? category.value : '')).trim()
  const slug = keyword.toLowerCase().replace(/&/g,' and ').replace(/[^a-z0-9\u0E00-\u0E7F]+/g,'-').replace(/^-|-$/g,'')
  const location = region.value === 'bangkok' ? '/in-Bangkok' : region.value === 'thailand' ? '/in-Thailand' : ''
  return `https://th.jobsdb.com/${slug ? `${encodeURIComponent(slug)}-jobs` : 'jobs'}${location}`
})
let timer:any
watch(searchDraft, value => { clearTimeout(timer); timer=setTimeout(()=>{query.value=value;visibleCount.value=36},350) })
watch(() => data.value.facets, facets => {
  if (pending.value || data.value.jobs.length || !facets.afterCategory) return
  if (minSalary.value && !Number(facets.salaryThresholds[String(minSalary.value)] || 0)) {
    const old = minSalary.value; minSalary.value = 0; flash(`ไม่มีงานช่วง ${old.toLocaleString()}+ บาท — แสดงทุกเงินเดือนแทน`); return
  }
  if (salaryOnly.value && !facets.salaryDisclosed) { salaryOnly.value=false; flash('ไม่มีประกาศที่แจ้งเงินเดือน — แสดงทุกงานแทน') }
}, { deep:true })
function isNew(date:string|null){ return !!date && Date.now()-new Date(date).getTime() < 72*60*60*1000 }
function posted(date:string|null){ if(!date)return 'Recently'; const hours=Math.max(1,Math.floor((Date.now()-new Date(date).getTime())/3600000)); return hours<24?`${hours}h ago`:`${Math.floor(hours/24)}d ago` }
function flash(message:string){toast.value=message;setTimeout(()=>toast.value='',2500)}
async function refreshFeeds(){refreshToken.value++;await refresh();refreshToken.value=0;flash('Fresh jobs loaded')}
async function save(job:DiscoveredJob){
  saving.value.add(job.key); saving.value=new Set(saving.value)
  try {
    await $fetch('/api/jobs',{method:'POST',body:{url:job.url,platform:job.source,title:job.title,company:job.company,location:job.location,workMode:job.workMode,salary:job.salary,notes:job.excerpt,tags:job.tags,postedAt:job.postedAt?.slice(0,10)||null}})
    job.isTracked=true; flash('Saved to your pipeline')
  } catch(e:any){ if(e?.status===409||e?.statusCode===409){job.isTracked=true;flash('Already in your pipeline')}else flash(e?.data?.statusMessage||'Could not save this job') }
  finally{saving.value.delete(job.key);saving.value=new Set(saving.value)}
}
async function dismiss(job:DiscoveredJob){await $fetch('/api/discover/dismiss',{method:'POST',body:{key:job.key,dismissed:!job.isDismissed}});job.isDismissed=!job.isDismissed;flash(job.isDismissed?'Hidden from Discover':'Restored')}
function resetFilters(){ searchDraft.value='';query.value='';category.value='all';employment.value='all';minSalary.value=0;salaryOnly.value=false;visibleCount.value=36 }
function salaryCount(value:number){ return Number(data.value.facets.salaryThresholds[String(value)] || 0) }
</script>

<template>
  <div class="min-h-screen">
    <header class="sticky top-0 z-30 border-b bg-canvas/90 backdrop-blur"><div class="mx-auto flex max-w-[1500px] items-center justify-between px-5 py-4 lg:px-8">
      <NuxtLink to="/" class="flex items-center gap-3"><div class="grid h-10 w-10 place-items-center rounded-xl bg-ink text-lime"><BriefcaseBusiness :size="20"/></div><div><h1 class="font-display text-xl leading-none">First Move</h1><p class="mt-1 text-[10px] font-bold uppercase tracking-[.18em] text-muted">Job command center</p></div></NuxtLink>
      <nav class="flex rounded-xl border bg-white/70 p-1"><NuxtLink to="/" class="flex items-center gap-2 rounded-lg px-3 py-2 text-xs font-semibold text-muted hover:text-ink"><LayoutDashboard :size="16"/><span class="hidden sm:inline">Pipeline</span></NuxtLink><NuxtLink to="/discover" class="flex items-center gap-2 rounded-lg bg-ink px-3 py-2 text-xs font-semibold text-white"><Radar :size="16"/>Discover</NuxtLink></nav>
    </div></header>

    <main class="mx-auto max-w-[1500px] px-5 py-8 lg:px-8">
      <section class="relative mb-8 overflow-hidden rounded-[2rem] bg-ink px-6 py-9 text-white sm:px-10 sm:py-12"><div class="absolute -right-20 -top-28 h-80 w-80 rounded-full border-[55px] border-lime/10"></div><div class="absolute bottom-0 right-1/4 h-24 w-24 rounded-full bg-rust/20 blur-2xl"></div><div class="relative flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><div class="mb-4 inline-flex items-center gap-2 rounded-full bg-lime/15 px-3 py-1.5 text-xs font-semibold text-lime"><Sparkles :size="14"/> 6 live API sources + JobsDB</div><h2 class="max-w-2xl font-display text-4xl leading-tight sm:text-5xl">The next good role<br>might have landed <em class="text-lime">today.</em></h2></div><div class="grid grid-cols-3 gap-3 lg:w-[26rem]"><div class="rounded-2xl bg-white/10 p-4"><strong class="text-2xl">{{jobs.length}}</strong><p class="mt-1 text-xs text-white/60">Matches</p></div><div class="rounded-2xl bg-white/10 p-4"><strong class="text-2xl">{{newCount}}</strong><p class="mt-1 text-xs text-white/60">New 72h</p></div><div class="rounded-2xl bg-white/10 p-4"><strong class="text-2xl">{{disclosedSalaryCount}}</strong><p class="mt-1 text-xs text-white/60">With salary</p></div></div></div></section>

      <section class="mb-6 rounded-2xl border bg-panel p-3 shadow-card"><div class="flex flex-col gap-3 xl:flex-row"><label class="relative flex-1"><Search class="absolute left-3.5 top-3 text-muted" :size="18"/><input v-model="searchDraft" class="field !bg-canvas pl-10" placeholder="ค้นหาตำแหน่ง ทักษะ บริษัท หรือเขต…"></label><div class="grid grid-cols-2 gap-2 sm:flex"><select v-model="region" class="field min-w-32"><option value="bangkok">Bangkok</option><option value="thailand">Thailand</option><option value="apac">APAC</option><option value="all">Worldwide</option></select><select v-model="source" class="field min-w-36"><option value="all">All 6 API sources</option><option value="thaidoe">ไทยมีงานทำ</option><option value="jobopportunities">Job Opportunities</option><option value="jobicy">Jobicy</option><option value="remoteok">Remote OK</option><option value="remotive">Remotive</option><option value="remotelanders">Remote Landers</option></select><button class="btn-secondary col-span-2 whitespace-nowrap sm:col-span-1" :disabled="pending" @click="refreshFeeds"><RefreshCw :size="16" :class="{'animate-spin':pending}"/> Refresh</button></div></div>
        <div class="mt-3 grid gap-2 border-t pt-3 sm:grid-cols-2 lg:grid-cols-[1.4fr_1fr_1fr_auto_auto]"><label class="relative"><SlidersHorizontal class="absolute left-3 top-3 text-muted" :size="15"/><select v-model="category" class="field pl-9"><option value="all">ทุกสายงาน ({{data.facets.total}})</option><option v-for="item in DISCOVERY_CATEGORIES" :key="item" :value="item" :disabled="!data.facets.categories[item]">{{item}} ({{data.facets.categories[item] || 0}})</option></select></label><select v-model="employment" class="field"><option value="all">ทุกประเภทงาน</option><option value="ประจำ">ประจำ</option><option value="full">Full-time</option><option value="part">Part-time</option><option value="contract">Contract</option><option value="intern">Internship</option></select><label v-if="localSalary" class="relative"><CircleDollarSign class="absolute left-3 top-3 text-muted" :size="15"/><select v-model.number="minSalary" class="field pl-9"><option :value="0">เงินเดือนเท่าไรก็ได้ ({{data.facets.afterCategory}})</option><option :value="15000" :disabled="!salaryCount(15000)">15,000+ THB/เดือน ({{salaryCount(15000)}})</option><option :value="20000" :disabled="!salaryCount(20000)">20,000+ THB/เดือน ({{salaryCount(20000)}})</option><option :value="30000" :disabled="!salaryCount(30000)">30,000+ THB/เดือน ({{salaryCount(30000)}})</option><option :value="50000" :disabled="!salaryCount(50000)">50,000+ THB/เดือน ({{salaryCount(50000)}})</option><option :value="80000" :disabled="!salaryCount(80000)">80,000+ THB/เดือน ({{salaryCount(80000)}})</option></select></label><label class="flex items-center gap-2 rounded-xl border bg-white px-3 py-2 text-xs font-semibold"><input v-model="salaryOnly" type="checkbox" class="h-4 w-4 accent-moss"> มีเงินเดือน ({{data.facets.salaryDisclosed}})</label><button class="btn-secondary !px-3" title="Reset filters" @click="resetFilters"><RotateCcw :size="15"/><span class="lg:hidden">ล้างตัวกรอง</span></button></div>
        <div class="mt-3 flex items-center justify-between border-t px-1 pt-3 text-xs text-muted"><span v-if="data.fetchedAt">พบ <strong class="text-ink">{{jobs.length}}</strong> งาน · จาก {{data.facets.total}} งาน · Updated {{ new Date(data.fetchedAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}) }}</span><span v-else>Connecting to job feeds…</span><button v-if="hiddenCount" class="flex items-center gap-1.5 font-semibold hover:text-ink" @click="showDismissed=!showDismissed"><EyeOff :size="14"/> {{showDismissed?'Hide':'Show'}} {{hiddenCount}} dismissed</button></div></section>

      <section class="mb-6 flex flex-col gap-4 rounded-2xl border border-[#e3c55d]/60 bg-[#fff8dc] p-5 shadow-card sm:flex-row sm:items-center sm:justify-between"><div><div class="mb-1 flex items-center gap-2"><span class="rounded-md bg-[#ffd400] px-2 py-1 text-[10px] font-black uppercase tracking-wider text-black">JobsDB</span><h3 class="font-semibold">ค้นงานใน JobsDB ด้วยตัวกรองนี้</h3></div><p class="text-xs leading-relaxed text-muted">JobsDB ไม่มี public search API สำหรับผู้สมัคร ปุ่มนี้จึงเปิดผลค้นหาทางการโดยตรง · เจอแล้วกด Save ผ่าน Quick Add ได้</p></div><a :href="jobsDbUrl" target="_blank" rel="noopener" class="btn-primary shrink-0 !bg-black !text-white hover:!bg-black/80">เปิด JobsDB <ArrowUpRight :size="16"/></a></section>

      <div v-if="pending && !data.jobs.length" class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div v-for="i in 9" :key="i" class="h-64 animate-pulse rounded-2xl bg-ink/5"></div></div>
      <div v-else-if="error" class="rounded-3xl border border-red-100 bg-red-50 px-6 py-16 text-center"><Radar class="mx-auto mb-4 text-red-400" :size="30"/><h3 class="font-display text-2xl">The feeds are taking a break.</h3><p class="mt-2 text-sm text-muted">Try refreshing in a moment. Your pipeline is unaffected.</p><button class="btn-secondary mt-5" @click="refreshFeeds"><RefreshCw :size="16"/> Try again</button></div>
      <div v-else-if="!visible.length" class="rounded-3xl border border-dashed px-6 py-16 text-center"><Search class="mx-auto mb-4 text-muted" :size="28"/><h3 class="font-display text-2xl">เงื่อนไขนี้ยังไม่มีงานที่ตรงครับ</h3><p class="mx-auto mt-2 max-w-xl text-sm leading-relaxed text-muted">มีงานในพื้นที่ {{data.facets.total}} งาน แต่ไม่มีงานที่ผ่านทุกตัวกรองพร้อมกัน ลองผ่อนเงื่อนไขด้านล่างเพื่อดูงานใกล้เคียง</p><div class="mt-6 flex flex-wrap justify-center gap-2"><button v-if="minSalary" class="btn-primary" @click="minSalary=0"><CircleDollarSign :size="16"/> ไม่จำกัดเงินเดือน</button><button v-if="salaryOnly" class="btn-secondary" @click="salaryOnly=false">รวมงานที่ไม่แจ้งเงินเดือน</button><button v-if="category!=='all'" class="btn-secondary" @click="category='all'">ดูทุกสายงาน</button><button class="btn-secondary" @click="resetFilters"><RotateCcw :size="16"/> ล้างตัวกรองทั้งหมด</button></div></div>
      <section v-else class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
        <article v-for="job in visible" :key="job.key" class="group flex min-h-72 flex-col rounded-2xl border bg-panel p-5 shadow-card transition hover:-translate-y-1 hover:shadow-soft" :class="{'opacity-50':job.isDismissed}">
          <div class="mb-4 flex items-start justify-between gap-3"><div class="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-ink text-sm font-bold text-lime">{{job.company.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}}</div><div class="flex items-center gap-1.5"><span v-if="isNew(job.postedAt)" class="rounded-full bg-lime px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider">New</span><span class="rounded-full bg-ink/5 px-2.5 py-1 text-[10px] font-bold text-muted">{{job.source}}</span><button class="rounded-full p-1.5 text-muted hover:bg-red-50 hover:text-red-600" :title="job.isDismissed?'Restore':'Not interested'" @click="dismiss(job)"><component :is="job.isDismissed?RefreshCw:X" :size="15"/></button></div></div>
          <p class="mb-2 text-[10px] font-bold uppercase tracking-[.13em] text-rust">{{job.category}}</p><h3 class="text-base font-semibold leading-snug">{{job.title}}</h3><p class="mt-1 text-sm text-muted">{{job.company}}</p><div class="mt-3 flex flex-wrap gap-x-3 gap-y-1 text-xs text-muted"><span class="flex items-center gap-1"><MapPin :size="13"/>{{job.location}}</span><span class="flex items-center gap-1"><Clock3 :size="13"/>{{posted(job.postedAt)}}</span></div><p v-if="job.salary" class="mt-3 flex items-center gap-1.5 text-xs font-semibold text-moss"><CircleDollarSign :size="14"/>{{job.salary}}</p><p v-else class="mt-3 text-xs text-muted/60">Salary not disclosed</p><p class="mt-3 line-clamp-3 text-xs leading-relaxed text-muted">{{job.excerpt}}</p><div class="mt-3 flex flex-wrap gap-1"><span v-for="tag in job.tags.slice(0,3)" :key="tag" class="rounded-md bg-ink/5 px-2 py-1 text-[10px] text-muted">{{tag}}</span></div>
          <div class="mt-auto flex items-center gap-2 border-t pt-4"><a :href="job.url" target="_blank" rel="noopener" class="flex flex-1 items-center gap-1.5 text-xs font-semibold text-moss hover:underline"><ExternalLink :size="14"/> View role</a><button class="btn !rounded-lg !px-3 !py-2 text-xs" :class="job.isTracked?'bg-emerald-50 text-emerald-700':'bg-ink text-white hover:bg-moss'" :disabled="job.isTracked||saving.has(job.key)" @click="save(job)"><Check v-if="job.isTracked" :size="14"/><BookmarkPlus v-else :size="14"/>{{job.isTracked?'Saved':saving.has(job.key)?'Saving…':'Save'}}</button></div>
        </article>
      </section>
      <button v-if="visibleCount<jobs.length" class="btn-secondary mx-auto mt-8 flex" @click="visibleCount+=36">Show more opportunities</button>
      <footer class="mt-12 border-t py-8 text-center text-xs leading-relaxed text-muted">Jobs provided by <a class="font-semibold text-ink underline" href="https://xn--72c5abh2bf8icw0m9d.doe.go.th/searchjobmap" target="_blank">ไทยมีงานทำ — กรมการจัดหางาน</a>, <a class="font-semibold text-ink underline" href="https://www.jobopportunitiesapi.org" target="_blank">Job Opportunities API</a>, <a class="font-semibold text-ink underline" href="https://jobicy.com" target="_blank">Jobicy</a>, <a class="font-semibold text-ink underline" href="https://remoteok.com" target="_blank">Remote OK</a>, <a class="font-semibold text-ink underline" href="https://remotive.com" target="_blank">Remotive</a> and <a class="font-semibold text-ink underline" href="https://remotelanders.com" target="_blank">Remote Landers</a>.<br>JobsDB opens its official search page. Salary periods and currencies follow each source; always verify details before applying.</footer>
    </main>
    <Transition name="fade"><div v-if="toast" class="fixed bottom-6 left-1/2 z-50 flex -translate-x-1/2 items-center gap-2 rounded-full bg-ink px-5 py-3 text-sm font-semibold text-white shadow-soft"><Check :size="16" class="text-lime"/>{{toast}}</div></Transition>
  </div>
</template>
